# Generated by Django 2.1.2 on 2018-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181022_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
