# Generated by Django 2.1.2 on 2018-10-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('cover', models.CharField(blank=True, max_length=20183, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('synopsis', models.CharField(blank=True, max_length=4000, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('item_no', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('isbn', models.ForeignKey(db_column='isbn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app1.Books')),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
